version: '3'

services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang-app
    container_name: app-prod
    environment:
      - ENVIRONMENT=PROD
    networks:
      - proxy-network
      - prod

networks:
  proxy-network:
    external: true
  prod:
