version: '3'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang-app
    container_name: app-dev
    environment:
      - ENVIRONMENT=DEV
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true